import { Card, Row, Col, Image, Button } from "react-bootstrap";
import { Link } from "react-router-dom";
import Browse from "../pages/browse";

import Vivienne from '../images/vivienne.jpg';

export default function Russo() {
    return (
        <section>
            <header>
                <Browse />
                <div className="book-padding">
                    <Row>
                        <Col sm={3}>
                            <Card>
                                <Card.Body>
                                    <Image src={Vivienne} style={{ height: "400px", width: "255px" }} />
                                </Card.Body>
                            </Card>
                        </Col>
                        <Col sm={9}>
                            <div>
                                <h1><strong>Vivienne</strong></h1>
                                <h4>Emmalea Russo</h4>
                                <hr />
                                <h5>Description:</h5>
                                <p>
                                    Did Vivienne Volker kill Wilma Lang? This question has dogged Vivienne
                                    ever since Wilma jumped from a window to her death shortly after Volker
                                    stole her lover, the visionary artist Hans Bellmer, in the 1970s. Once
                                    a famous artist and fashion icon, Volker is now in her eighties and
                                    spends her days in religious contemplation in rural Pennsylvania
                                    alongside her daughter Velour Bellmer, her granddaughter Vesta Furio,
                                    her much younger boyfriend—a garbageman named Lou—and Franz, the family
                                    dog. Their quiet lives are disrupted when Vivienne's work is selected
                                    for inclusion in a high-profile retrospective called "Forgotten Women
                                    Surrealists" at the prestigious NAT Museum. However, when rumors of her
                                    past misdeeds begin to circulate and she is dropped from the show, a
                                    gallery curator enters the picture hoping to capitalize on the buzz
                                    generated by the controversy, sending the family's tensions, hopes,
                                    and dreams to a dizzying peak. Set over the course of a fateful week,
                                    Vivienne deftly weaves surreal prose with a Greek chorus of internet
                                    comments and text messages, to ask the what is the cost of vision,
                                    what is the price of art?
                                </p>
                                <hr />
                                <Row>
                                    <Col sm={3}>
                                        <h6>Tags:</h6>
                                        <ul>
                                            <li>
                                                Art
                                            </li>
                                            <li>
                                                Fiction
                                            </li>
                                            <li>
                                                Literary Fiction
                                            </li>
                                        </ul>
                                    </Col>
                                    <Col sm={1}>
                                        <div style={{ width: "1px", height: "13rem", backgroundColor: "black" }}></div>
                                    </Col>
                                    <Col sm={4} style={{ textAlign: "left" }}>
                                        <h6>This edition</h6>
                                        <hr />
                                        <Row>
                                            <Col sm={6}>
                                                Format
                                            </Col>
                                            <Col sm={6}>
                                                264 pages
                                            </Col>
                                        </Row>
                                        <hr />
                                        <Row>
                                            <Col sm={6}>
                                                Published
                                            </Col>
                                            <Col sm={6}>
                                                2024
                                            </Col>
                                        </Row>
                                        <hr />
                                        <Row>
                                            <Col sm={6}>
                                                Language
                                            </Col>
                                            <Col sm={6}>
                                                English
                                            </Col>
                                        </Row>
                                    </Col>
                                    <Col sm={1}>
                                        <div style={{ width: "1px", height: "13rem", backgroundColor: "black" }}></div>
                                    </Col>
                                    <Col sm={3} style={{ textAlign: "center" }}>
                                        <Card style={{ marginTop: "20px", marginBottom: "20px" }}>
                                            <Card.Body>
                                                <h6>
                                                    Pricing
                                                </h6>
                                                <h4>
                                                    Rp99.999
                                                </h4>
                                            </Card.Body>
                                        </Card>
                                        <Link to="/browse/art/vivienne/checkout">
                                            <Button type="checkout">Buy Now</Button>
                                        </Link>
                                    </Col>
                                </Row>
                            </div>
                        </Col>
                    </Row>
                </div>
            </header>
        </section>
    )
}